### ISSUE TITLE
Installing Neuron-Library

### ISSUE THREAD

**Issue by MortezaAliyari** [Adlink-ROS/camera_trigger_daemon#2]
Hi there,
I was running based on tutorial to install Neuron-library and by running:
 ``` curl -L --insecure https://neuron.adlinktech.com/debian/repo_signing.key | sudo apt-key add -```
 i'm facing below error :
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: neuron.adlinktech.com
gpg: no valid OpenPGP data found.

 ```
 i want to use camera_trigger_daemon python code. im using Roscube-X series(RQX-58g).
 Thanks for your support

**Comment by QQting** [comment]
Hi @MortezaAliyari , 

We no longer maintain the server: "neuron.adlinktech.com".
Please go to below link to download Neuron Library
https://github.com/Adlink-ROS/mraa/releases/tag/1.3.13

By the way, can I know your company information and what's your system architecture for using camera_trigger_daemon?
And I'm also curious about how did you find camera_trigger_daemon?

Thank you.

**Comment by MortezaAliyari** [comment]
Thanks for quick response @QQting 
Kingwaytek.
search

**Comment by QQting** [comment]
Hi @MortezaAliyari 

Okay, I just got one RQX-58G back from Kingwaytek because the FPGA firmware was wrong.
Can you check the FPGA firmware version? 

```
i2cget -f -y 2 0x66 0x01
```

The result should be 0x24.
If you can't get the version, the FSYNC function will not work.

**Comment by MortezaAliyari** [comment]
@QQting
I executed:
```
sudo python3 adlink_camera_sync.py sync -f 1 -t 0
```
I connected the pps signal to pin 5(GPIO 0). so i'm expecting the two cameras which are connecting to channel 1 and 2 work with 1 fps. but im facing below error :
```
/bin/sh: 1: cannot create /sys/module/leopard_ar0233/parameters/trigger_mode: Directory nonexistent
Set to frame Sync mode
Error: Write failed
```
and about Traceback (most recent call last):
```
  File "adlink_camera_sync.py", line 240, in <module>
    MyDaemon.run_sync()
  File "adlink_camera_sync.py", line 168, in run_sync
    self.daemonize()
  File "adlink_camera_sync.py", line 125, in daemonize
    so = open(self.stdout, 'a+')
FileNotFoundError: [Errno 2] No such file or directory: '/home/ros/camera_trigger_daemon/daemon.log'
```

Also I executed:
```
i2cget -f -y 2 0x66 0x01
```
result is :
```
Error: Read failed
```
So is it mean i can't sync the cameras with external signal?!
which versions will work?

**Comment by MortezaAliyari** [comment]
Also i have another question about ``` adlink_camera_sync.py```.
By running this file is it possible to run the camera driver launch file and compare timestamp info of two cameras?
I mean is it necessary to run ``` adlink_camera_sync.py``` every time i need to capture frames or use camera?
thanks again

**Comment by QQting** [comment]
As I know, you are using Tier IV Camera, not Leopard AR0233, right?
This python script is a sample code using to manually trigger AR0233 camera shutter.
For Tier IV camera users, please go to `/etc/modprobe.d/` to enable the trigger_mode.
But the Tier IV trigger_mode only works when RQX FPGA version is at least 0x24.

In 0x24 FPGA firmware, there are two Fsync mode:
- Fsync Auto Trigger mode
- Fsync Manual Trigger mode

In auto trigger mode, the FPGA can trigger multiple cameras at the same time automatically, no user program is needed to involved.

The FPGA of RQX-58G can be only upgraded by connecting to JTAG. So you may send the RQX-58G back to ADLINK for flashing the FPGA firmware in order to use frame sync.

**Comment by MortezaAliyari** [comment]
The company already sent one of them to be upgraded. So I will wait to that
one and check the code again.
Thanks 👍
